version: "3.8"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true